services:
  my_mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=learnDocker
      - MYSQL_USER=daniel
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
  
    # To initialize MYSQL db with relevent schemas
    # Copied local init directory into container's /docker-entrypoint-initdb.d directory
    # https://hub.docker.com/_/mysql#:~:text=Initializing%20a%20fresh%20instance
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  my_node_app:
    build: ./app
    ports:
      - "4000:4000"
    volumes:
      - ./app:/usr/src/app
    restart: always
    depends_on:
      - my_mysql_db
